spring:
  application:
    name: collector
  datasource:
    url: jdbc:mariadb://localhost:3306/test_collect
    username: collector
    password: 6382
    driver-class-name: org.mariadb.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
#  file config(filepath: 저장경로 / filename: 파일명 / fileExtension: 파일 확장자)
filegen:
  filepath: D:\myProject\SolomonPj
  filename: 연간월평균
  fileExtension: xls
  fileheader: MONTH, ROAD_NAME, DIR_NAME, ST_NAME, ED_NAME, DISTANCE, 평일평균, 주말평균, 전체평균
exception_sender:
  connector:
    url: http://192.168.0.111:14766/api/notifications
    max_retry_count: 3      # 최대 재시도 횟수
    retry_delay_ms: 2000    # 재시도 대기 시간 (밀리초)
    connection_timeout_ms: 5000  # 연결 타임아웃 시간 (밀리초)
  message:
    sender: sixthgkrsus@naver.com
    recipients: -1002166045687
    title: 파일생성 에러
    deliveryType: TELEGRAM

